package view;

import controller.UsuarioDAO;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class formLogin extends javax.swing.JFrame {

    public formLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        txtLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Login");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(62, 44, 60, 16);

        btnEntrar.setBackground(new java.awt.Color(204, 204, 204));
        btnEntrar.setForeground(new java.awt.Color(51, 51, 51));
        btnEntrar.setText("Entrar");
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar);
        btnEntrar.setBounds(160, 220, 136, 37);

        txtLogin.setBackground(new java.awt.Color(204, 204, 204));
        txtLogin.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtLogin);
        txtLogin.setBounds(62, 78, 332, 22);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Senha");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(62, 118, 70, 16);

        txtSenha.setBackground(new java.awt.Color(204, 204, 204));
        txtSenha.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtSenha);
        txtSenha.setBounds(62, 152, 332, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        String login = txtLogin.getText();
        String senha = txtSenha.getText();

        UsuarioDAO u = new UsuarioDAO();

        if (login.equals("admin") && senha.equals("1234")) {
            this.setVisible(false);
            formCadastro objCadastro = new formCadastro();
            objCadastro.setVisible(true);
            objCadastro.setTitle("admin logado - " + login);
        } else {

            try {
                ResultSet resul = u.validarLogin(login, senha);

                if (resul.next()) {
                    int nivel = resul.getInt("id_Nivel_Admin");

                    switch (nivel) {
                        case 0:
                            this.setVisible(false);
                            formComprovante objComprovante = new formComprovante();
                            objComprovante.setVisible(true);
                            objComprovante.setTitle("caixa logado - " + login);
                            break;

                        case 1:
                            this.setVisible(false);
                            formPedido objPedido = new formPedido();
                            objPedido.setVisible(true);
                            objPedido.setTitle("funcionario logado - " + login);
                            break;

                        case 2:
                            this.setVisible(false);
                            formCadastro objCadastro = new formCadastro();
                            objCadastro.setVisible(true);
                            objCadastro.setTitle("admin logado - " + login);
                            break;

                    }
                } else {
                    JOptionPane.showConfirmDialog(
                            null,
                            "Usuário ou Senha Inválido",
                            "Erro na Operação",
                            JOptionPane.WARNING_MESSAGE);
                    txtLogin.requestFocus();
                    txtLogin.setText("");
                    txtSenha.setText("");
                }

            } catch (SQLException err) {
                JOptionPane.showMessageDialog(null, err.getMessage());
            }

        }
    }//GEN-LAST:event_btnEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
